"""baseline

Revision ID: 001_baseline
Revises:
Create Date: 2026-04-11 00:36:19.364121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "001_baseline"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('model_url', sa.Text(), nullable=True),
    sa.Column('model_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('modelo_url', sa.Text(), nullable=False),
    sa.Column('modelo_path', sa.Text(), nullable=True),
    sa.Column('material', sa.String(length=10), nullable=False),
    sa.Column('escala', sa.Float(), nullable=False),
    sa.Column('peso_gramas', sa.Float(), nullable=False),
    sa.Column('volume_cm3', sa.Float(), nullable=False),
    sa.Column('tempo_impressao_horas', sa.Float(), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.Column('frete_centavos', sa.Integer(), nullable=False),
    sa.Column('cep_destino', sa.String(length=8), nullable=False),
    sa.Column('prazo_dias', sa.Integer(), nullable=False),
    sa.Column('codigo_rastreio', sa.String(length=50), nullable=True),
    sa.Column('mp_payment_id', sa.String(length=100), nullable=True),
    sa.Column('mp_preference_id', sa.String(length=100), nullable=True),
    sa.Column('progresso_percentual', sa.Integer(), nullable=True),
    sa.Column('camada_atual', sa.Integer(), nullable=True),
    sa.Column('camada_total', sa.Integer(), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('erro_em', sa.DateTime(), nullable=True),
    sa.Column('impressao_iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('impressao_concluida_em', sa.DateTime(), nullable=True),
    sa.Column('arquivo_3mf_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('generations')
    # ### end Alembic commands ###
